
URLRefresh: http://tracking.bcscdepot.com/refresh
Booking:
  RefreshDays: -60

Laden: 

Database:
  Debug : true
  Password : X7NZe7>56B9[u&%9
  Port : 1433
  Server : 192.168.56.103
  User : tracking
  Name : DCMSBCSC